// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {inspect} from '../models';

export function ActivateWindow(arg1:inspect.ActivateWindowRequest):Promise<inspect.ActivateWindowResponse>;

export function ClearHighlight(arg1:inspect.ClearHighlightRequest):Promise<inspect.ClearHighlightResponse>;

export function CopyBestSelector(arg1:inspect.CopyBestSelectorRequest):Promise<inspect.CopyBestSelectorResponse>;

export function GetElementUnderCursor(arg1:inspect.GetElementUnderCursorRequest):Promise<inspect.GetElementUnderCursorResponse>;

export function GetFocusedElement(arg1:inspect.GetFocusedElementRequest):Promise<inspect.GetFocusedElementResponse>;

export function GetNodeChildren(arg1:inspect.GetNodeChildrenRequest):Promise<inspect.GetNodeChildrenResponse>;

export function GetNodeDetails(arg1:inspect.GetNodeDetailsRequest):Promise<inspect.GetNodeDetailsResponse>;

export function GetPatternActions(arg1:inspect.GetPatternActionsRequest):Promise<inspect.GetPatternActionsResponse>;

export function GetTreeRoot(arg1:inspect.GetTreeRootRequest):Promise<inspect.GetTreeRootResponse>;

export function HighlightNode(arg1:inspect.HighlightNodeRequest):Promise<inspect.HighlightNodeResponse>;

export function InspectWindow(arg1:inspect.InspectWindowRequest):Promise<inspect.InspectWindowResponse>;

export function InvokePattern(arg1:inspect.InvokePatternRequest):Promise<inspect.InvokePatternResponse>;

export function ListWindows(arg1:inspect.ListWindowsRequest):Promise<inspect.ListWindowsResponse>;

export function RefreshWindows(arg1:inspect.RefreshWindowsRequest):Promise<inspect.RefreshWindowsResponse>;

export function SelectNode(arg1:inspect.SelectNodeRequest):Promise<inspect.SelectNodeResponse>;

export function SetEventEmitter(arg1:any):Promise<void>;

export function ToggleFollowCursor(arg1:inspect.ToggleFollowCursorRequest):Promise<inspect.ToggleFollowCursorResponse>;
