// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateWindow(arg1) {
  return window['go']['main']['ViewerApp']['ActivateWindow'](arg1);
}

export function ClearHighlight(arg1) {
  return window['go']['main']['ViewerApp']['ClearHighlight'](arg1);
}

export function CopyBestSelector(arg1) {
  return window['go']['main']['ViewerApp']['CopyBestSelector'](arg1);
}

export function GetElementUnderCursor(arg1) {
  return window['go']['main']['ViewerApp']['GetElementUnderCursor'](arg1);
}

export function GetFocusedElement(arg1) {
  return window['go']['main']['ViewerApp']['GetFocusedElement'](arg1);
}

export function GetNodeChildren(arg1) {
  return window['go']['main']['ViewerApp']['GetNodeChildren'](arg1);
}

export function GetNodeDetails(arg1) {
  return window['go']['main']['ViewerApp']['GetNodeDetails'](arg1);
}

export function GetPatternActions(arg1) {
  return window['go']['main']['ViewerApp']['GetPatternActions'](arg1);
}

export function GetTreeRoot(arg1) {
  return window['go']['main']['ViewerApp']['GetTreeRoot'](arg1);
}

export function HighlightNode(arg1) {
  return window['go']['main']['ViewerApp']['HighlightNode'](arg1);
}

export function InspectWindow(arg1) {
  return window['go']['main']['ViewerApp']['InspectWindow'](arg1);
}

export function InvokePattern(arg1) {
  return window['go']['main']['ViewerApp']['InvokePattern'](arg1);
}

export function ListWindows(arg1) {
  return window['go']['main']['ViewerApp']['ListWindows'](arg1);
}

export function RefreshWindows(arg1) {
  return window['go']['main']['ViewerApp']['RefreshWindows'](arg1);
}

export function SelectNode(arg1) {
  return window['go']['main']['ViewerApp']['SelectNode'](arg1);
}

export function SetEventEmitter(arg1) {
  return window['go']['main']['ViewerApp']['SetEventEmitter'](arg1);
}

export function ToggleFollowCursor(arg1) {
  return window['go']['main']['ViewerApp']['ToggleFollowCursor'](arg1);
}
